### ISSUE TITLE
Friend's pronouns in the french translation is plural they/them

### ISSUE THREAD

**Issue by Terofale** [TRSasasusu/TranslationForTheOutsider#27]
In french, we don't really have a singular they/them pronoun, it's either singular gendered pronoun or plural gendered pronoun. In the translation Friend's pronouns is "ils" which is masculine plural. We have a non-gendered pronoun ("iel"), but it isn't really used outside of queer spaces. I can make a fork and change it to either "il" (masculine singular) or iel, and also while I'm at it fix some translation issues, and PR it back. What do you think is the best way to translate it ?

**Comment by TRSasasusu** [comment]
@Terofale hmm... it seems difficult problem...

I think you can refer to Hearthians, which has no gender in many languages except French (and maybe some languages?)
I heard some Hearthians have genders in French, so you can follow such a style for translation of Friend.

@Fighters91 , @Myalgul and @Chaxiraxi , do you have some opinions?

**Comment by Chaxiraxi** [comment]
Hard to say. I launched the game in the fresh 1.1.14 release, and after wandering in the Hearthian village, I figured out that translators have made incredibly careful work not to use any French gendered pronouns, and always use Hearthian's names instead of using the He/She equivalent. They/Them equivalent for non-gendered people is inexistent in the French language, except for non-binary people who use "iel", a newly invented pronoun that is the concatenation of gendered pronouns "il" and "elle". Instead, They/Them literally translates into the masculine plural pronoun "ils".

With that said, it is very difficult to make a decision considering that it would take a political turn due to the changing society and the rise of wokism. Not using "iel" for obviously ungendered people would be considered a clear offence to the LGBTIQ+ community while using it will be considered an insult to the French language and admit being the victim of the woke propaganda. The right decision to please everyone would be the same as the original translators of the base game have done, which is not using pronouns at all, and referring to Hearthians and Friend by their names instead, which requires a lot of work reviewing once again every single text string of the mod....

Edit: After a bit of reflection, it is right that in French, something ungendered falls by default under the masculine pronoun ("it" being inexistent in French, we only have he/she equivalent), so using it could be a solution. And since this is an alien race, I don't think not using "iel" is an actual problem. That would be too extreme to see a political opinion here for arbitrarily setting a masculine gender to an ungendered alien race because of French grammar rules. This applies to both Hearthians and Friend (although I still think the best solution is not using pronouns at all like in the base game)

**Comment by Myalgul** [comment]
Hey there !
The joyce of translating something without a gender into French :D 
The first time I saw "They/them" being used, I knew that was here to means that it was ungenred, but while doing the translation, i choose to use "ils", being the literal translation of "They/them" (masculine by default and plural). Starting from that, i based all my correction of the first rough translation on using this pronouns, and I'm by no means a pro translator so...

Now, without getting political, if you think "il" or even "iel" would be more appropriate, go for it ! I saw two french guys playing it on Twitch and neither of them was shocked by the use of "ils". Another one just played it in English :) 
Like @Chaxiraxi said, changing it would mean to change many things (don't count on the replace tools for that). 

Don't forget we're here to be as close as possible to the original translation !

**Comment by TRSasasusu** [comment]
Hi, everyone.
[This project is finally integrated into The Outsider!](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/pull/13) (and this repository is archived now)
So, if you continue this discussion, you can go to The Outsider repository as a new issue with mentioning this issue's url.
