### ISSUE TITLE
Italian translation.

### ISSUE THREAD

**Issue by NerYtheLonesomeHearthian** [TRSasasusu/TranslationForTheOutsider#33]
Hello. I made an Italian translation. I upload the file here. Its extension had to be changed to .txt for the upload.
Thank you for making this mod! ::)
[italian.txt](https://github.com/TRSasasusu/TranslationForTheOutsider/files/14474514/italian.txt)

**Comment by TRSasasusu** [comment]
Thanks!
It is released in [v1.5.0](https://github.com/TRSasasusu/TranslationForTheOutsider/releases/tag/v1.5.0).

If you noticed the missed `/` in the line 1670, it's no problem because I fixed it in [this commit](https://github.com/TRSasasusu/TranslationForTheOutsider/commit/6a190f67fb745f65a226f6fc06e20310f6481e86) ::)

**Comment by NerYtheLonesomeHearthian** [comment]
I didn't notice actually, thanks for fixing it! 
I did my best to proofread the whole file, but I may have missed some typos. In that case I will let you know when i find them (I am planning to replay the whole mod with a friend).
I'm happy my translation is online, thank you again for doing this! ::D
